### ISSUE TITLE
Variogram not working

### ISSUE THREAD

**Issue by Jing25** [mmaelicke/scikit-gstat#39] opened 2020-08-24 01:05 UTC
Hi, I'm wondering if this toolkit is still being maintained? I cannot run the examples on your website. I installed version. 0.2.7

**Comment by mmaelicke** [comment] 2020-08-24 08:01
Hey,
Yes I am still maintaining scikit-gstat. What exactly is not working? I will need some more information to help or identify bugs that need fixes.

Best,
Mirko

**Comment by Jing25** [comment] 2020-08-24 18:46
I installed it with pip install scikit-gstat and run it with jupyter notebook. I started from this: https://scikit-gstat.readthedocs.io/en/latest/getting_started.html

<img width="480" alt="image" src="https://user-images.githubusercontent.com/27107288/91082772-02d21e00-e5fe-11ea-8d85-95525672da0d.png">

Everytime I run this line `V = Variogram(coordinates=coordinates, values=values)`, the kernel will restart. You can see in the image, there's a star in front of that cell showing it's running but it's not running. The kernel restarts without any sign and I have to run all cells from the beginning.

Not only in this example, I tested different examples, and Variogram() doesn't work as I expected. It just cleans up my kernel.. 

The version of my python is 3.7.6

**Comment by mmaelicke** [comment] 2020-08-25 06:23
Hey,

I can't reproduce the error on a clean Python 3.7.6. Can you please try to run the code outside of jupyter? That's very strange and I can't imagine a way how the Variogram could cause this kind of behavior. If it happens outside of jupyter as well, please report if there is any output or error. Please also try to run the code in a clean environment like:

```bash
conda create -n test python=3.7 numpy scipy pandas shapely numba scikit-learn scikit-gstat
```
Best

**Comment by Jing25** [comment] 2020-08-25 06:39
Sorry, I didn't find which conda channel scikit-gstat is available?

**Comment by mmaelicke** [comment] 2020-08-25 06:49
sorry, it's too early....
scikit-gstat is not available through conda. Omit the scikit-gstat and only install the others via conda. Then with activated environment, pip install scikit-gstat.

From my expericence it's better to install espcially shapely and scipy with conda, as they come with preinstalled binaries and installation via pip sometimes fails, especially on Windows systems.

Sorry for the confusion.

**Comment by Jing25** [comment] 2020-08-25 06:57
Ah..great it works! Thanks for the timely reply. It's the environment issue. A clean environment works.

**Comment by mmaelicke** [comment] 2020-08-25 07:01
Glad it works. I'll close this issue then. 
Best
Mirko

**Closed by mmaelicke** 2020-08-25 07:01 UTC
