### ISSUE TITLE
scikit

### ISSUE THREAD

**Issue by variog** [mmaelicke/scikit-gstat#14] opened 2018-11-13 14:54 UTC
pip install scikit-gstat

Command "python setup.py egg_info" failed with error code 1 in C:\Users\Parisa\AppData\Local\Temp\pip-install-lk9uyp93\shapely\

**Comment by mmaelicke** [comment] 2018-11-13 15:04
Thanks for submitting this issue.
From what I can see from your post, the installation of shapely is not working correctly. As a first shot, can you try to run: 

```bash
pip install shapely
```
and tell me if that works? Which OS are you using?

However, I will dig into this a bit deeper and come back to this issue asap.

**Comment by variog** [comment] 2018-11-13 15:14
I try:
pip install shapely
Command "python setup.py egg_info" failed with error code 1 in C:\Users\Parisa\AppData\Local\Temp\pip-install-chjsvvff\shapely\

    On Tuesday, November 13, 2018, 6:34:04 PM GMT+3:30, Mirko Mälicke <notifications@github.com> wrote:  
 
 
Thanks for submitting this issue.
From what I can see from your post, the installation of shapely is not working correctly. As a first shot, can you try to run:
pip install shapely
and tell me if that works? Which OS are you using?

However, I will dig into this a bit deeper and come back to this issue asap.

**Comment by variog** [comment] 2018-11-13 16:04
How can i mute the thread

**Comment by variog** [comment] 2018-11-13 16:39
![error](https://user-images.githubusercontent.com/45007613/48428279-eeea5e80-e77f-11e8-9539-a5b3cc667d27.png)

**Comment by variog** [comment] 2018-11-14 05:39
please help me to solve this problem

**Comment by mmaelicke** [comment] 2018-11-14 05:58
Yeah, I'm on it. It was just night for the last couple of hours in my time zone :-)

Ok, so far I could reproduce the error on my Windows machine in a clean Python environment and it seems to be a building problem of shapely. On Linux everything works fine. Please have a look at [this thread on GIS stackexchange](https://gis.stackexchange.com/questions/62925/why-is-shapely-not-installing-correctly/62931), it describes one solution to this issue. From your screenshot, I can see you are using Python 3.5, so installing the same wheel as described in the link should be fine.

The other solution you could try is to use virtualenv or preferably [Anaconda](https://www.anaconda.com/download/#windows) to manage your Python environments. This does not only keep you environement a bit more clean and makes bugfixing easier, they also have many prebuild packages in their repositories. With anaconda installed, you can create a new env like:
```bash
conda create -n test ipython shapely
conda activate test
pip install shapely
```
Just as a side note: from my experience it is also a good idea to install numpy, scipy and numba using conda and not pip. There are also a lot of resources explaining anaconda in case you want to use it.
 I hope this helps.

**Comment by variog** [comment] 2018-11-14 06:40
Sorry, this problem confused me
I check this solution and report it

**Comment by variog** [comment] 2018-11-14 09:56
Resolved, Thank you so much

**Comment by mmaelicke** [comment] 2018-11-14 10:01
Great. Would you mind sharing how you solved the problem for others? Then I can close the issue.

**Comment by variog** [comment] 2018-11-14 14:07
no problem

**Comment by variog** [comment] 2018-11-14 14:10
I did everything you said
conda create -n test ipython shapely
conda activate test
pip install shapely

**Comment by mmaelicke** [comment] 2018-11-16 10:10
perfect.

**Closed by mmaelicke** 2018-11-16 10:10 UTC

**Comment by variog** [comment] 2019-01-11 10:18
HelloI hope you have a happy time,
I already asked for guidance and you helped me very well,
I want to do Geostatistical work and I use this site http://www.ccgalberta.com/pygeostat/pythonintro.htmlbut when I want install pygeostat, require username and password.how to install this module?
