### ISSUE TITLE
Variogram plot issue

### ISSUE THREAD

**Issue by victortm** [mmaelicke/scikit-gstat#26] opened 2020-02-03 10:19 UTC
Hi,

I'm trying to reproduce the same example of https://scikit-gstat.readthedocs.io/en/latest/getting_started.html but I'm getting the next error:

![image](https://user-images.githubusercontent.com/10722495/73644676-1cb60e80-4676-11ea-8326-ae3af2b3cfff.png)

It seems related to V.plot() line. I don't know why matplotlib fails if I'm using the variogram plotting method. I tried also removing matplotlib lines but error still persist.

Thanks in advance and best regards

**Comment by mmaelicke** [comment] 2020-02-03 10:57
Hey,

Thanks for reporting.

Can you give me a minimal example and show the code you actually run? Otherwise will be hard for me to reproduce the error. The example code did not throw any error for me. Please, also give me the version you are running. You can find it running the line:
```python
import skgstat as skg
print(skg.__version__)
```

Next, the error message seems to originate from matplotlib backend. Have you tried to run a plot without the scikit-gstat package included? E.g.
```python
import matplotlib.pyplot as plt
plt.figure()
plt.plot([0,1,2,3,4], [1,3,1,2], '.-k')
plt.show()
```
If the error still persists in that example (without skgstat), I would try to search for the error directly. 
A quick search gave me eg [this post](https://stackoverflow.com/questions/29540845/how-can-i-deactivate-warning-source-id-510-was-not-found-when-attempting-to-re)

I hope this helps.
Best

Mirko

**Comment by victortm** [comment] 2020-02-03 17:25
Of course.

It is exactly same code you have on the website:

`from skgstat import Variogram
import numpy as np
import matplotlib.pyplot as plt

plt.style.use('ggplot')

np.random.seed(42)

coordinates = np.random.gamma(20, 5, (50,2))

np.random.seed(42)

values = np.random.normal(20, 5, 50)

V = Variogram(coordinates=coordinates, values=values)

print(V)

V.plot()`

The version is 0.2.7

![image](https://user-images.githubusercontent.com/10722495/73675087-1776b500-46b2-11ea-83bf-8903015b5c15.png)

And seems matplotlib works fine without scikit-gstat:

![image](https://user-images.githubusercontent.com/10722495/73675248-560c6f80-46b2-11ea-9ce8-af3812b4ef42.png)

Thanks n regards

**Comment by victortm** [comment] 2020-02-03 17:58
Right now I've installed the 0.2.8 version and then I ran the code obtaining same error.

**Comment by mmaelicke** [comment] 2020-02-03 18:01
Thanks, I am right now trying to reproduce the error. Can you give me your matplotlib version as well?

**Comment by mmaelicke** [comment] 2020-02-03 18:25
Ok, I think I am getting closer. To me it seems like the backend of matplotlib is the problem. I am not sure, why the simple plot is working and scikit-gstat plot is not working. I am not a matplotlib expert. Nevertheless, when I tried to use the GTK3 backend, which you seem to be using, I ran into some installation problems. The backend needs pycairo as a dependency, which needs cairo, which is as far as I understand it not available for Python 3.  Maybe you can give me some details, how you make the backend work in a Python 3 environment. But maybe I am also missing something here...

However, you can change the backend like:
```python
import matplotlib
matplotlib.use('TkAgg')
```
this works fine on my linux machine.  I also installed a Python 3.6.9, like shown on your screenshot. 

One thing we could try is to run the plot differently e.g.:
```python
fig = V.plot(show=False)
fig.show()
```
This way you should get the matplotlib.Figure returned. Another possible pathway would be to create the figure beforehand and plot the variogram:

```python
fig, axes = plt.subplots(2, 1)
V.plot(axes=axes)
fig.show()
```
Maybe the subplots are the problem, then we could leave the histogram away:
```python
V.plot(hist=False)
```
Or build the figure externally, all together:
```python
# experimental variogram
plt.plot(V.bins, V.experimental, '.b')

# model
x = np.linspace(0, max(V.bins), 100)
plt.plot(x, list(map(V.fitted_model, x)), '-g')
plt.gcf().show()
```
The last thing should work as the plot function never gets called. 
Elsewise, I have no further idea. I will continue to try to install the backend, in order to reproduce the error, but first I have to bring my kids into bed :)

**Comment by victortm** [comment] 2020-02-04 10:46
Hi,

I've got installed matplotlib 3.1.3 version:

![image](https://user-images.githubusercontent.com/10722495/73733092-9e23a480-473b-11ea-83a2-28010b94e5cd.png)

These are the results of all options you've provided:

Once I've changed matplotlib backend:
```
import matplotlib
matplotlib.use('TkAgg')
```

A)
```
fig = V.plot(show=False)
fig.show()
```
There's no error but it doesn't represent anything.

B)
```
fig, axes = plt.subplots(2, 1)
V.plot(axes=axes)
fig.show()
```
Same behaviour as A option.

C)
```
V.plot(hist=False)
```
Same as A and B options.

D)
```
# experimental variogram
plt.plot(V.bins, V.experimental, '.b')

# model
x = np.linspace(0, max(V.bins), 100)
plt.plot(x, list(map(V.fitted_model, x)), '-g')
plt.gcf().show()
```
D has no errors but it doesn't represent anything either.

In conclusion for all alternatives, there's no error but they doesn't reprensent any graphic. Maybe using another backend?

Regarding to GTK3 backend, I didn't know what you were talking about and I had to search some info about 'matplotlib backends' so I can not give you much more details. All I can say is that when I tried to run:
```
import matplotlib.pyplot as plt
plt.figure()
plt.plot([0,1,2,3], [1,3,1,2], '.-k')
plt.show()
```

I didn't write anything extra, I just ran the code as it shows in the example.

Also, I didn't tell you but I tried to work using python 2.7.17. When I installed scikit-gstat by git clone method:

```
git clone https://github.com/mmaelicke/scikit-gstat.git
cd scikit-gstat
pip install -r requirements.txt
python setup.py install
```
I get the next error:

![image](https://user-images.githubusercontent.com/10722495/73736540-37a18500-4741-11ea-8226-666ee5288bd5.png)

And when I try to run the script We're working on I get same error:

![image](https://user-images.githubusercontent.com/10722495/73736629-63bd0600-4741-11ea-8576-9b4f0a516384.png)

My idea at first moment was to work with python 2.7 but when I found that error and then I had no problems installing on python 3.6, that's why I continued using python 3.6. This is extra info that is not related to the problem we're facing right now. But I thought maybe using that previous python version matplotlib has no problems.

Thanks for all your support, I really appreciate it.

**Comment by mmaelicke** [comment] 2020-02-04 12:03
Ok. Running scikit-gstat on Python 2.X is not possible. It needs at least 3.5. 

I am not completely sure what you mean by 
>D has no errors but it doesn't represent anything either.
>In conclusion for all alternatives, there's no error but they doesn't reprensent any graphic.

Is there an error or is there no error? What do you mean by the figure doesn't represent anything? I am a bit confused now.
When using `TkAgg` matplotlib backend, a new window should open each time ``fig.show()`` or ``plt.plot( [...] )`` gets called.
Maybe it would be helpful to show me the console output from either of the examples.  And also please specify from where you are running the python interpreter: did you run `ipython` or `python` command? Are you using the terminal application from linux or did you start something like the QtConsole distributed e.g. with ananconda?

Thanks

**Comment by victortm** [comment] 2020-02-04 13:02
There's no error. The error I attached when I opened the issue is not showing anymore. However, there's no graphic represenation of the variogram, it doesn't open a new window.

I write the code on gedit and then run the script on linux (18.04) console as follows:

```
python3 script.py
```

This is the ouput:

![image](https://user-images.githubusercontent.com/10722495/73746674-07b0ac80-4756-11ea-9bff-79ec147d8f0a.png)

Please, let me know if you don't understand something. Hope it is clearer now.

Thanks

**Comment by mmaelicke** [comment] 2020-02-04 13:35
Ahh, ok. You are running a script. 
I thought you are using the interpreter directly (interactive mode) for debugging. Well, then the plot is most likely there, but will immediately be closed as the script finishes. To verify, use the interpreter directly. This is how the examples in the documentation are meant, maybe I have to clarify this.

However, you should then be able to obtain a plot by preventing the script from finishing. Or save the figure as png (or whatsoever), like:
```python
fig = V.plot()
fig.savefig('variogram.png')
```
What I don't understand is that you reported the plain matplotlib example to stay open? Because it shouldn't.

This is not related to scikit-gstat anymore, but basic Python script writing. Therefore, in case you can confirm that scikit-gstat actually did produce a figure, I will close the issue.
Best

Mirko

**Comment by victortm** [comment] 2020-02-04 13:55
Ok, now it's working.

Maybe if I had started explaining my workflow...my bad.

You can close this issue.

Thank you so much for your help

**Comment by mmaelicke** [comment] 2020-02-04 13:58
Glad it works now. Thanks!

**Closed by mmaelicke** 2020-02-04 13:58 UTC
