### ISSUE TITLE
Leave one out nan predicted values

### ISSUE THREAD

**Issue by victortm** [mmaelicke/scikit-gstat#33] opened 2020-04-16 10:39 UTC
Hi,

Im trying to evaluate how good are the predictions by leave one out method and I'm getting nan results in some scenarios.

So, in this case I'm trying to predict sample values that I already know and then calculate the error comparing with the original data. I wrote a simple loop that predict one by one the values of a known sample list:

```
from skgstat import Variogram, OrdinaryKriging
import pandas as pd
import numpy as np 
import matplotlib.pyplot as plt
from pprint import pprint
import matplotlib
from sklearn.metrics import mean_squared_error

plt.style.use('ggplot')

matplotlib.use('TkAgg')

# Data processing
data = pd.read_csv('madrid_NOx.txt',sep =';',decimal=',')

data = data.drop(['DATE','HEIGHT','OK'],axis=1)
data['DATE'] = pd.to_datetime(data.DATETIME,dayfirst=True)
data = data.drop(['DATETIME'],axis=1)

# Scenario selection
subgroup = data[data.DATE == '2018-03-30 04:00:00']
subgroup.reset_index(inplace=True)

# Leave one out
# Predicted values store
pdic = ([])

for i in range(0,len(subgroup.index)):
# Reset sample list
	aux = subgroup
	
# Get the value coordinates to predict
	x = np.array([aux.loc[i,'LON']])
	y = np.array([aux.loc[i,'LAT']])

# Remove the point we want to predict from the list
	aux = aux.drop([aux.index[i]])

# Variogram and kriging functions
	v = Variogram(aux[['LON', 'LAT']].values, aux.DATA.values,normalize=False, model='spherical')
	ok = OrdinaryKriging(v,mode='exact',min_points=5,max_points=10)

# pval --> predicted value
	pval = ok.transform(x, y)

# tval --> original value
	tval = np.array([subgroup.loc[i,'DATA']])

	pdic.append(pval)
	print('Test value: {}'.format(tval))
	print('Predicted value: {}'.format(pval))

# Error formula
#rms = np.sqrt(mean_squared_error(np.array(subgroup.DATA),np.array(pdic)))
#print(rms)
```

The problem is that I get nan predicted values when sample values are low. Same does not happen when I'm working with high values. In both cases I'm using same number of samples, 24. So I don't understand why there's no enough neighbors when I'm working with the same number of samples, the only thing that change is the values, coordinates keep still.

Thanks and best regards

**Comment by mmaelicke** [comment] 2020-04-16 17:57
Hey, 

I will just post the two files you sent me by mail here as well, for reference.

* [low_values.txt](https://github.com/mmaelicke/scikit-gstat/files/4488779/low_values-1.txt)
* [high_values.txt](https://github.com/mmaelicke/scikit-gstat/files/4488780/high_values-1.txt)

Unfortunately, I am missing the `madrid_NOx.txt` to run your code. Could you post this? Or send it by mail and I will update this post.

Now, to the NaN values:
My first thought was that with `min_points=5`, you might run into instances where there are not 5 other points within the variogram range. In your code, you are using the default setting of `maxlag='median'`, which will use the median of all separating distances.
Thus, given the coordinates in the two files posted above are the same as in the file I don't have, you are using a maxlag of

```python
import numpy as np
from scipy.spatial.distance import pdist
np.median(data[['LON', 'LAT']])
```
of `564191.3240948275` . Which would be about one tickmark in the image shown below. Note that the **range** will be smaller than maxlag.

![image](https://user-images.githubusercontent.com/2826034/79488011-5cf02080-8019-11ea-9ad0-fa67dd702555.png)

Therefore, I would expect the at least the marked points **not** to find 5 neighbors within the range and thus returning `nan` as a result, which is expected behavior. 

But to be clear: This is just what I am expecting, we can have a closer look once I have the correct file and/or checked the calculation step by step (on it...). 

As a general workaround for situations like this:
You will always run into *'outliers'* that can't find enough neighbors. My personal suggestion would be to omit these results and keep track of how many have been omitted to either take the cross-validation result or drop it. 
In your case replacing:
```python
pdic.append(pval)
```
with
```python
  if np.isnan(pval):
    nancounter += 1
    print('Omitted point %d' % i)
  else:
    pdic.append(pval)
    print('Test value: {}'.format(tval))
    print('Predicted value: {}'.format(pval))  
```

`nancounter=0` has to be defined outside the loop and before you calculate the `rms` you can check how often that happened. If just 4-5 times, I would not care, if more often, I would tweak the params again (like using a smaller value for `min_points` or setting a `maxlag` directly or to `None`.)

I will check out your code step by step as soon as I find the time

**Comment by mmaelicke** [comment] 2020-04-16 18:00
Hey man,

Sorry, just realizing that the default value for `maxlag` is already `None` and not `median`. So please ignore the part about maxlag.
Nevertheless, the range should approx. be around 1.6 Mio. So 1 and a half tickmarks on the image. That might still not be enough to find enough neighbors?

**Comment by victortm** [comment] 2020-04-20 10:31
Hi,

Thanks for the suggestion, I really appreciate it.

I played with the min and max points parameters in both cases.

Working with low values, seems like the less points you set, the less nan values you'll obtain. And if you increase the min/max points, then nan results increase too until the case I showed you first when I opened the issue, that just obtain one non nan predicted value.

However, there's no different behaviour using high values, there's no nan results when I change min/max points parameters.

Could it be a bug?

Thanks and best regards

**Comment by mmaelicke** [comment] 2020-04-20 16:50
Hey,

I am still trying to understand what is happening. I'm into it. But I have to admit that I have only a limited amount of time at the moment.

**Comment by mmaelicke** [comment] 2020-04-29 07:16
Sorry for me taking so long to reply.

I could confirm that the problem is the effective range. Consider that the values are different in your low and high value example. This directly affects the semi-variance values calculated, which in turn affects the actual model parameters. The effective range is a model parameter, that Kriging uses to find observations within the range. I calculated two variograms as given in your example:

![image](https://user-images.githubusercontent.com/2826034/80569295-eb40ab00-89f8-11ea-933f-98eae5d40c70.png)

`V` is based on the high values, `V2` on the low values. If you plot both, you can see what's going wrong. The effective range is way to short for the low values, which I could confirm as:

```python
from scipy.spatial.distance import pdist
dm = pdist(low_data[['LON', 'LAT']])
print(len(dm))
print(sum(dm > V.describe()['effective_range']))
print(sum(dm > V2.describe()['effective_range']))
```
This yields:
```
276
9
249
```
That means: we have `276` point pairs available in total, which is not a lot. For the high values, only 9 of them are outside the effective range of your variogram. That's fine. But for the low values, almost all point pairs are outside and we will have a hard time finding those `276 - 249 = 27` cases that Kriging will use.

So my suggestion is to carefully look at the plot of what I called `V2` and make sure that this is a valid variogram. Try to find one that matches the data and has a larger effective range. But it is also possible that this can't be done as there might be no spatial structure in the data, or we have too few observations. In both cases you would have to admit that Kriging is not the right tool, though.
From my point of view this is sometimes necessary, statistics should not find something that is not in the data...
Let me know, if you find a suitable Variogram or abandon the low values.
Best,

Mirko

**Comment by mmaelicke** [comment] 2020-05-12 12:40
I will consider this as solved and close the issue.
You can re-open if anything still needs to be discussed or is unclear.

**Closed by mmaelicke** 2020-05-12 12:40 UTC
Labels: question
