### ISSUE TITLE
azimuth for directional variogram class

### ISSUE THREAD

**Issue by jshiriyev** [mmaelicke/scikit-gstat#32] opened 2020-03-27 22:11 UTC
Hello,

I have a simple exercise where I calculated the directional experimental variogram manually.
Using the directional variogram class I am trying to get the same number but could not.

The case for 45 degrees does not give the exact same result. I attached the word document.

[00_variogram.docx](https://github.com/mmaelicke/scikit-gstat/files/4396119/00_variogram.docx)

**Comment by mmaelicke** [comment] 2020-03-28 10:44
Hey Javid,

Thanks for submitting this issue.
I will have a look at the exercise, but I have to say that I don't have too much time at the moment due to home office and childcare (schools are closed here in Germany). 

Could you also share the Python code you used to create the directional variogram? 

Thanks and best,
Mirko

**Comment by jshiriyev** [comment] 2020-03-28 11:46
Hello Mirko,

First of all thanks for the reply.

Below I attached the code and text file of the data shown on the word document.
I believe the second gamma.experimental value should give me 161.75 as in the word document.
I tried both plus and minus 45 degrees for azimuth, but still not getting the value. I also tried different directional models.

I appreciate your work and stay safe!

Javid

[data.txt](https://github.com/mmaelicke/scikit-gstat/files/4397046/data.txt)

import numpy as np
import skgstat as skg

data = np.loadtxt("data.txt")

gamma = skg.DirectionalVariogram(data[:,0:2],
                                 data[:,2],n_lags=3,
                                 azimuth=45,tolerance=22.5,
                                 directional_model='triangle')

print(gamma.bins)
print(gamma.experimental)

**Comment by mmaelicke** [comment] 2020-04-02 08:43
I've got it! I know what's going on. Unfortunately, the answer is long and because of Corona I am at home with my children. I will try to edit this answer as soon as they let me or have their nap. Sorry.

**Comment by mmaelicke** [comment] 2020-04-02 10:22
OK. Took me some time to notice. First of all: The exercise is asking for the semi-variance value at *precisely* `20*sqrt(2)` ft. The `Variogram.bins` are lag class bin *edges*. That means a bin class with `20*sqrt(2)` as value will use all distance values from the lower edge **up to the upper edge**. This is at least how I understand the solution in the exercise. The `Variogram.experimental` array will give you the semi-variance for the whole classes. 

There is a possibility to calculate the exercise with skgstat anyway. Beware that **calculating the result without skgstat is more straightforward and possibly easier**. If you want to apply it to more or larger data sets, do as follows:

First, the `Variogram` has a property called `Variogram.distance` returning the flattened, upper triangle of the distance matrix. From this, we can filter all distance very close to `20*sqrt(2)`. Do not use the exact distance due to rounding errors. `DirectionalVariogram` has a function, which was designed for internal use called `DirectionalVariogram._direction_mask`. This will return a boolean array of same shape as the 1D distance array indicating which point pairs are within the search geometry defined in `DirectionalVariogram`. Combining both, the indices of the point pairs we need can be found like:

```python
V = DirectionalVariogram( ... )  # put your code here from above

found = np.where((abs(V.distance -  20*np.sqrt(2)) < 0.01) & V._direction_mask())
```

The `Variogram` class does also calculate the differences (or distances) in **value** for all point pairs. The array has again the same layout. It is called `Variogram._diff` and was also designed for internal use. Now you can grap the correct values from here and pass them to the desired estimator from the `skgstat.estimators` class, or implement your own.

```python
skg.estimators.matheron(V._diff[found])
```

which yields `161.75`.

I hope this helps and I will close the issue as it seems to yield the same results. If anything is not clear, feel free to re-open.
Best
Mirko

**Closed by mmaelicke** 2020-04-02 10:22 UTC

**Comment by jshiriyev** [comment] 2020-04-02 10:47
Thank you very much, Mirko,
I will implement the procedure as you said.
